### ISSUE TITLE
Empty Output

### ISSUE THREAD

**Issue by byemypast** [polyactis/Accucopy#14]
Dear author,
I am running Accucopy on a batch of low-coverage WGS data. All raw-data were mapped with BWA(grch37 provided on document chapter 3.7), and marked with picard.
Some of the bams have ideal results, while the others have empty output in infer.out.tsv and infer.out.details.tsv.

the last 20 lines of infer.status.txt are shown below,
`_segment_stddev_divider=20
_snp_maf_stddev_divider=20
_snp_covearge_min=2
_snp_coverage_var_vs_mean_ratio=10
_no_of_peaks_for_logL=3
Reading SNPs from /gpfs/share/home/1601111669/WGS_15/accucopy_result//MLPS_ZJW_C/het_snp.tsv.gz ...
22 chromosomes, 423742 SNPs, 570146 lines.
Reading in segments from /gpfs/share/home/1601111669/WGS_15/accucopy_result//MLPS_ZJW_C/all_segments.tsv.gz ...
Outputting segment ratio data to /gpfs/share/home/1601111669/WGS_15/accucopy_result//MLPS_ZJW_C/rc_ratio_window_count_smoothed.tsv...Done.
Outputting segment ratio data to /gpfs/share/home/1601111669/WGS_15/accucopy_result//MLPS_ZJW_C/rc_ratio_no_of_windows_by_chr.tsv...Done.
32 segments. 32 segments used. 423717 SNPs used.
Calculating auto correlation ...Done.
Outputting SNP logORs by segments to /gpfs/share/home/1601111669/WGS_15/accucopy_result//MLPS_ZJW_C/snp_logOR_by_segment.tsv ... 32 segments.
Calculating auto correlation shift-1 difference ...
#mean is: 0, sigma is: 0.0010521
Done.
Inferring candidate periods through GADA, run_type=1, left_x=-0.000266546, right_x=0.000266546 ...
Initiating GADA instance ...GADA done
Found 0 candidate periods.
ERROR: No candidate period discovered.
`

Could you please kindly suggest the reason GADA found 0 candidate and if there's sth I can done?

Best Regards,
Junyi

**Comment by byemypast** [comment]
And Error logs of HPC are shown below. could it be mistake of multi-thread?
====================================


[2021-11-24T09:24:24.559817] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] Completed command task: 'gzip_rc_ratio_no_of_windows_by_chr' launched from master workflow
[2021-11-24T09:24:25.127531] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] Completed command task: 'plot_tre' launched from master workflow
[2021-11-24T09:24:25.494502] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] Failed to complete command task: 'plot_model_select' launched from master workflow, error code: 1, command: '/usr/local/Accucopy/plot_model_select_result.py -f /gpfs/share/home/1601111669/WGS_15/accucopy_result//ASPS_WSXM_C/model_selection_log/model_selection.h5 -o /gpfs/share/home/1601111669/WGS_15/accucopy_result//ASPS_WSXM_C/model_selection_log'
[2021-11-24T09:24:25.497249] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [plot_model_select] Error Message:
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [plot_model_select] Last 12 stderr lines from task (of 12 total lines):
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.417057] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select] /gpfs/share/home/1601111669/WGS_15/accucopy_result//ASPS_WSXM_C/model_selection_log aleady exists.
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.418192] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select] Traceback (most recent call last):
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.419200] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]   File "/usr/local/Accucopy/plot_model_select_result.py", line 60, in <module>
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.420194] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]     f = h5py.File(args.file, 'r')
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.421240] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]   File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.422304] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]     fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.423282] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]   File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.424318] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]     fid = h5f.open(name, flags, fapl=fapl)
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.425347] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.426403] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.427351] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select]   File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5f.c:2129)
[2021-11-24T09:24:25.499751] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] [2021-11-24T09:24:25.428530] [a4u23n12.hpc.pku.edu.cn] [1202_1] [plot_model_select] IOError: Unable to open file (unable to open file: name = '/gpfs/share/home/1601111669/WGS_15/accucopy_result//ASPS_WSXM_C/model_selection_log/model_selection.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2021-11-24T09:24:25.503259] [a4u23n12.hpc.pku.edu.cn] [1202_1] [TaskManager] [ERROR] Shutting down task submission. Waiting for remaining tasks to complete.

**Comment by fanxinping** [comment]
Hi, Maybe the failed samples have a noisy TRE plot. You can refer to `Section 6.2 A clean-data example` and `Section 6.3 A noisy-data example` in `https://www.yfish.org/display/PUB/Accucopy` and use the `plot.tre.png` to judge whether the sample is too noisy for Accucopy. Accucopy will fail to find candidate period on extremely noisy data.
The error logs you provided in the second message means `plot_model_select_result.py` raises `No such file or directory` error. Because Accucopy failed on the sample, so it failed to output some files, such as `model_selection.h5`, which is used by `plot_model_select_result.py`.

**Comment by byemypast** [comment]
Thanks for your kindly advice & Have a good day :D
Thanks again for the great work!
